name: CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        id: lint
        run: npm run lint
        continue-on-error: true

      - name: Run lint --fix if needed
        if: steps.lint.outcome == 'failure'
        run: npm run lint -- --fix

      - name: Run tests
        run: npm test
